version: '3'
services:
    postgres:
        build: ./docker/postgres/
        restart: unless-stopped
        environment:
            POSTGRES_USER: open_city_profile
            POSTGRES_PASSWORD: open_city_profile
            POSTGRES_DB: open_city_profile
        ports:
            - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: profile-db

    django:
        build:
            context: ./
            dockerfile: ./docker/django/Dockerfile
        command: bash -c 'tail -f /dev/null'
        env_file:
            - ./.env
        environment:
            DATABASE_URL: postgres://open_city_profile:open_city_profile@profile-db/open_city_profile
        volumes:
            - .:/code
            - django-media-volume:/var/media/
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        container_name: profile-backend

volumes:
        pgdata:
            driver: local
        django-media-volume:
